2025-03-19 19:11:46	INFO	::casa	
2025-03-19 19:11:46	INFO	::casa	
2025-03-19 19:11:46	INFO	::casa	
2025-03-19 19:11:46	INFO	::casa	
2025-03-19 19:11:47	INFO	::casa	Python version 3.8.10
2025-03-19 19:11:47	INFO	::casa	CASA Version PIPELINE 6.6.1.17
2025-03-19 19:11:47	INFO	::casa	
2025-03-19 19:11:48	INFO	::casa	optional configuration file config.py not found, continuing CASA startup without it
2025-03-19 19:11:48	INFO	::casa	
2025-03-19 19:11:48	INFO	::casa	Checking Measures tables in data repository sub-directory /usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casadata/__data__/geodetic
2025-03-19 19:11:48	INFO	::casa	  IERSeop2000 (version date, last date in table (UTC)): 2024/06/22/15:00, 2024/05/23/00:00:00
2025-03-19 19:11:48	INFO	::casa	  IERSeop97 (version date, last date in table (UTC)): 2024/06/22/15:00, 2024/05/23/00:00:00
2025-03-19 19:11:48	INFO	::casa	  IERSpredict (version date, last date in table (UTC)): 2024/06/23/15:00, 2024/09/21/00:00:00
2025-03-19 19:11:48	INFO	::casa	  TAI_UTC (version date, last date in table (UTC)): 2024/05/24/15:00, 2017/01/01/00:00:00
2025-03-19 19:11:54	INFO	simobserve::::casa	##########################################
2025-03-19 19:11:54	INFO	simobserve::::casa	##### Begin Task: simobserve         #####
2025-03-19 19:11:54	INFO	simobserve::::casa	simobserve( project='C10_5_67968s', skymodel='RADMC3d_fits/CPD_PPD_PDS70_1620.5.fits', inbright='', indirection='J2000 14h08m10.11s -41d23m52.95s', incell='0.002arcsec', incenter='185 GHz', inwidth='', complist='', compwidth='"8GHz"', comp_nchan=1, setpointings=True, ptgfile='$project.ptg.txt', integration='30s', direction=[], mapsize=["''", "''"], maptype='ALMA', pointingspacing='', caldirection='', calflux='1Jy', obsmode='int', refdate='2025/01/01', hourangle='transit', totaltime='67968s', antennalist='alma.cycle11.10.cfg', sdantlist='aca.tp.cfg', sdant=0, outframe='LSRK', thermalnoise='tsys-atm', user_pwv=0.412, t_ground=269.0, t_sky=260.0, tau0=0.1, seed=11111, leakage=0.0, graphics='none', verbose=False, overwrite=True )
2025-03-19 19:11:54	WARN	simobserve::simutil::casa	Your skymodel 'RADMC3d_fits/CPD_PPD_PDS70_1620.5.fits' could not be found.
2025-03-19 19:11:54	SEVERE	simobserve::::casa	Exception Reported: Error in simobserve: No sky input found.  At least one of skymodel or complist must exist.
2025-03-19 19:11:54	INFO	simobserve::::casa	Traceback (most recent call last):
2025-03-19 19:11:54	INFO	simobserve::::casa+	  File "/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casashell/private/simobserve.py", line 1405, in __call__
2025-03-19 19:11:54	INFO	simobserve::::casa+	    task_result = _simobserve_t( _pc.document['project'],_pc.document['skymodel'],_pc.document['inbright'],_pc.document['indirection'],_pc.document['incell'],_pc.document['incenter'],_pc.document['inwidth'],_pc.document['complist'],_pc.document['compwidth'],_pc.document['comp_nchan'],_pc.document['setpointings'],_pc.document['ptgfile'],_pc.document['integration'],_pc.document['direction'],_pc.document['mapsize'],_pc.document['maptype'],_pc.document['pointingspacing'],_pc.document['caldirection'],_pc.document['calflux'],_pc.document['obsmode'],_pc.document['refdate'],_pc.document['hourangle'],_pc.document['totaltime'],_pc.document['antennalist'],_pc.document['sdantlist'],_pc.document['sdant'],_pc.document['outframe'],_pc.document['thermalnoise'],_pc.document['user_pwv'],_pc.document['t_ground'],_pc.document['t_sky'],_pc.document['tau0'],_pc.document['seed'],_pc.document['leakage'],_pc.document['graphics'],_pc.document['verbose'],_pc.document['overwrite'] )
2025-03-19 19:11:54	INFO	simobserve::::casa+	  File "/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casatasks/private/task_simobserve.py", line 166, in simobserve
2025-03-19 19:11:54	INFO	simobserve::::casa+	    msg("No sky input found."+
2025-03-19 19:11:54	INFO	simobserve::::casa+	  File "/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casatasks/private/simutil.py", line 254, in msg
2025-03-19 19:11:54	INFO	simobserve::::casa+	    raise Exception(s)
2025-03-19 19:11:54	INFO	simobserve::::casa+	Exception: No sky input found.  At least one of skymodel or complist must exist.
2025-03-19 19:11:54	INFO	simobserve::::casa	Task simobserve complete. Start time: 2025-03-19 19:11:53.702171 End time: 2025-03-19 19:11:53.720439
2025-03-19 19:11:54	INFO	simobserve::::casa	##### End Task: simobserve           #####
2025-03-19 19:11:54	INFO	simobserve::::casa	##########################################
2025-03-19 19:11:54	INFO	simanalyze::::casa	##########################################
2025-03-19 19:11:54	INFO	simanalyze::::casa	##### Begin Task: simanalyze         #####
2025-03-19 19:11:54	INFO	simanalyze::::casa	simanalyze( project='C10_10_679680s', image=True, imagename='default', skymodel='', vis='C10_10_67968s/C10_10_67968s.alma.cycle11.10.noisy.ms', modelimage='', imsize=[], imdirection='', cell='0.002arcsec', interactive=False, niter=0, threshold='0.1mJy', weighting='natural', mask=[], outertaper=[], pbcor=True, stokes='I', featherimage='', analyze=True, showuv=True, showpsf=True, showmodel=True, showconvolved=False, showclean=True, showresidual=False, showdifference=True, showfidelity=True, graphics='both', verbose=False, overwrite=True, dryrun=False, logfile='' )
2025-03-19 19:11:54	SEVERE	simanalyze::::casa	Exception Reported: Error in simanalyze: C10_10_679680s directory doesn't exist - the task expects to find results from creating the datasets there, like the skymodel.
2025-03-19 19:11:54	INFO	simanalyze::::casa	Traceback (most recent call last):
2025-03-19 19:11:54	INFO	simanalyze::::casa+	  File "/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casashell/private/simanalyze.py", line 1065, in __call__
2025-03-19 19:11:54	INFO	simanalyze::::casa+	    task_result = _simanalyze_t( _pc.document['project'],_pc.document['image'],_pc.document['imagename'],_pc.document['skymodel'],_pc.document['vis'],_pc.document['modelimage'],_pc.document['imsize'],_pc.document['imdirection'],_pc.document['cell'],_pc.document['interactive'],_pc.document['niter'],_pc.document['threshold'],_pc.document['weighting'],_pc.document['mask'],_pc.document['outertaper'],_pc.document['pbcor'],_pc.document['stokes'],_pc.document['featherimage'],_pc.document['analyze'],_pc.document['showuv'],_pc.document['showpsf'],_pc.document['showmodel'],_pc.document['showconvolved'],_pc.document['showclean'],_pc.document['showresidual'],_pc.document['showdifference'],_pc.document['showfidelity'],_pc.document['graphics'],_pc.document['verbose'],_pc.document['overwrite'],_pc.document['dryrun'],_pc.document['logfile'] )
2025-03-19 19:11:54	INFO	simanalyze::::casa+	  File "/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casatasks/private/task_simanalyze.py", line 76, in simanalyze
2025-03-19 19:11:54	INFO	simanalyze::::casa+	    msg(fileroot+" directory doesn't exist - the task expects to find results from creating the datasets there, like the skymodel.",priority="error")
2025-03-19 19:11:54	INFO	simanalyze::::casa+	  File "/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casatasks/private/simutil.py", line 254, in msg
2025-03-19 19:11:54	INFO	simanalyze::::casa+	    raise Exception(s)
2025-03-19 19:11:54	INFO	simanalyze::::casa+	Exception: C10_10_679680s directory doesn't exist - the task expects to find results from creating the datasets there, like the skymodel.
2025-03-19 19:11:54	INFO	simanalyze::::casa	Task simanalyze complete. Start time: 2025-03-19 19:11:53.736184 End time: 2025-03-19 19:11:53.744159
2025-03-19 19:11:54	INFO	simanalyze::::casa	##### End Task: simanalyze           #####
2025-03-19 19:11:54	INFO	simanalyze::::casa	##########################################
2025-03-19 19:11:54	SEVERE	exportfits::::casa	Exception Reported: Error in exportfits: the imagename parameter must be a path that exists ('C10_10_67968s/C10_10_67968s.alma.cycle11.10.noisy.image' does not exist)
2025-03-19 19:11:54	INFO	exportfits::::casa	Traceback (most recent call last):
2025-03-19 19:11:54	INFO	exportfits::::casa+	  File "/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casashell/private/exportfits.py", line 527, in __call__
2025-03-19 19:11:54	INFO	exportfits::::casa+	    assert _pc.validate(_invocation_parameters,self.__schema), create_error_string(_pc.errors)
2025-03-19 19:11:54	INFO	exportfits::::casa+	AssertionError: the imagename parameter must be a path that exists ('C10_10_67968s/C10_10_67968s.alma.cycle11.10.noisy.image' does not exist)
2025-03-19 19:12:23	INFO	simobserve::::casa	##########################################
2025-03-19 19:12:23	INFO	simobserve::::casa	##### Begin Task: simobserve         #####
2025-03-19 19:12:23	INFO	simobserve::::casa	simobserve( project='C10_5_67968s', skymodel='RADMC3d_fits/CPD_PPD_PDS70_1620.50.fits', inbright='', indirection='J2000 14h08m10.11s -41d23m52.95s', incell='0.002arcsec', incenter='185 GHz', inwidth='', complist='', compwidth='"8GHz"', comp_nchan=1, setpointings=True, ptgfile='$project.ptg.txt', integration='30s', direction=[], mapsize=["''", "''"], maptype='ALMA', pointingspacing='', caldirection='', calflux='1Jy', obsmode='int', refdate='2025/01/01', hourangle='transit', totaltime='67968s', antennalist='alma.cycle11.10.cfg', sdantlist='aca.tp.cfg', sdant=0, outframe='LSRK', thermalnoise='tsys-atm', user_pwv=0.412, t_ground=269.0, t_sky=260.0, tau0=0.1, seed=11111, leakage=0.0, graphics='none', verbose=False, overwrite=True )
2025-03-19 19:12:23	INFO	simobserve::FITSCoordinateUtil::fromFITSHeader	The WCS for this image contains 1 degenerate axes.
2025-03-19 19:12:23	INFO	simobserve::FITSImage::getImageAttributes 	Image dimension appears to be less than number of pixel axes in CoordinateSystem
2025-03-19 19:12:23	INFO	simobserve::FITSImage::getImageAttributes +	Adding 1 degenerate trailing axes
2025-03-19 19:12:23	INFO	simobserve::ImageFactory::createImage	Created Paged image 'C10_5_67968s/C10_5_67968s.alma.cycle11.10.skymodel' of shape [100, 100, 1, 1] with float valued pixels.
2025-03-19 19:12:24	INFO	simobserve::ImageFactory::fromImage	Created Paged image 'C10_5_67968s/C10_5_67968s.alma.cycle11.10.skymodel.flat' of shape [100, 100] with float valued pixels.
2025-03-19 19:12:24	INFO	simobserve::image::_adddegaxes 	Creating image 'C10_5_67968s/C10_5_67968s.alma.cycle11.10.skymodel.flat' of shape [100, 100, 1]
2025-03-19 19:12:24	INFO	simobserve::readantenna::casa	Reading antenna positions from '/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casadata/__data__/alma/simmos/alma.cycle11.10.cfg'
2025-03-19 19:12:24	INFO	simobserve::readantenna::casa	Reading antenna positions from '/usr/local/bin/CASA/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casadata/__data__/alma/simmos/alma.cycle11.10.cfg'
2025-03-19 19:12:24	INFO	simobserve::simobserve::casa	calculating map pointings centered at J2000 14:08:10.11000 -041.23.52.950000
2025-03-19 19:12:24	INFO	simobserve::calc_pointings::casa	using 1 generated pointing(s)
2025-03-19 19:12:24	INFO	simobserve::simobserve::casa	center = J2000 14:08:10.11000 -041.23.52.950000
2025-03-19 19:12:24	INFO	simobserve::simobserve::casa	preparing empty measurement set
2025-03-19 19:12:24	INFO	simobserve::simobserve::casa	You desire an hour angle of 0.0 hours
2025-03-19 19:12:25	INFO	simobserve::NewMSSimulator::initAnt() 	Using global coordinates for the antennas
2025-03-19 19:12:25	INFO	simobserve::NewMSSimulator::initAnt() 	Added rows to ANTENNA table
2025-03-19 19:12:25	INFO	simobserve::MSsimulator::initSpWindows() 	Creating new spectral window band2, ID 1
2025-03-19 19:12:25	INFO	simobserve::MSsimulator::initFeeds() 	Added rows to FEED table
2025-03-19 19:12:25	INFO	simobserve::simulator::settimes()	Times 
2025-03-19 19:12:25	INFO	simobserve::simulator::settimes()+	     Integration time 30s
2025-03-19 19:12:25	INFO	simobserve::simulator::settimes()	     Times will be interpreted as hour angles for first source
2025-03-19 19:12:26	SEVERE	simobserve::MeasTable::dUTC(Double) (file /source/casa6/casatools/casacore/measures/Measures/MeasTable.cc, line 4290)	Leap second table TAI_UTC seems out-of-date.
2025-03-19 19:12:26	SEVERE	simobserve::MeasTable::dUTC(Double) (file /source/casa6/casatools/casacore/measures/Measures/MeasTable.cc, line 4290)+	Until the table is updated (see the CASA documentation or your system admin),
2025-03-19 19:12:26	SEVERE	simobserve::MeasTable::dUTC(Double) (file /source/casa6/casatools/casacore/measures/Measures/MeasTable.cc, line 4290)+	times and coordinates derived from UTC could be wrong by 1s or more.
2025-03-19 19:12:26	INFO	simobserve::MeasIERS::fillMeas(MeasIERS::Files, Double) 	Requested JD 60676 is outside the range of the IERS (Earth axis data) table.
2025-03-19 19:12:26	INFO	simobserve::MeasIERS::fillMeas(MeasIERS::Files, Double) +	Calculations will proceed with less precision
2025-03-19 19:12:26	INFO	simobserve::NewMSSimulator::observe()	First source: C10_5_67968s.alma.cycle11.10_0 @ 14:08:10.11   -41.23.52.95       J2000
2025-03-19 19:12:26	INFO	simobserve::NewMSSimulator::observe()+	Full time range: 01-Jan-2025/02:31:22.6 -- 01-Jan-2025/21:24:22.6 TAI with int = 30
2025-03-19 19:12:26	INFO	simobserve::NewMSSimulator::observe()	Calculating a total of 2266 integrations
